### ISSUE TITLE
Create a valid maven repo for this API

### ISSUE THREAD

**Issue by alexandre14062** [chrismin13/AdditionsAPI#39]
It's complicated to make plugins using maven without having any valid repositories for this API
Can you create a new one with a GitHub plugin or whatever?

Thank you

**Comment by chrismin13** [comment]
You can try out jitpack.io. It generates Maven repositories out of any valid Github project. This is what I'm currently using in Vanilla Additions. Hopefully I'll switch over to the new Github Package Registry whenever I get into the beta!

In order to add jitpack to your maven repo you must add the following repository:

```
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
```

Depending on the version you want to use, you must also add the following dependency for Additions API for 1.13:
```
		<dependency>
			<groupId>com.github.chrismin13</groupId>
			<artifactId>additionsapi</artifactId>
			<version>spigot-1.13-SNAPSHOT</version>
		</dependency>
```
or the following for older 1.9 - 1.12 releases:
```
		<dependency>
			<groupId>com.github.chrismin13</groupId>
			<artifactId>additionsapi</artifactId>
			<version>master-SNAPSHOT</version>
		</dependency>
```
